#https://travis-ci.org/starobinskii/AiLibrary
sudo: false
language: c++
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
before_install:
script: make
after_success: ./app.out
coverity_scan:
    project:
      name: "starobinskii/AiLibrary"
      description: "C++ Library from Ailurus Studio"
    notification_email: dev@ailurus.ru
    build_command:   "make CXX=clang++"