name: AiLibrary
version: "1.1.0"
summary: C++ Library from Ailurus Studio
description: set of useful C++ functions to make your code work nice and fast.
grade: stable
confinement: strict

apps:
  hello:
    command: app.out

parts:
  gnu-hello:
    plugin: autotools
    source: https://github.com/starobinskii/AiLibrary/archive/v1.1.0.tar.gz