name: ailibrary
version: "1.1.0"
summary: C++ Library from Ailurus Studio
description: set of useful C++ functions to make your code work nice and fast.
grade: stable
confinement: strict

parts:
  ai:
    plugin: make
    source: git://github.com/starobinskii/AiLibrary.git
    source-type: git
    build-packages:
      - g++
      - make