name: ailibrary
version: "1.1.0"
summary: C++ Library from Ailurus Studio
description: set of useful C++ functions to make your code work nice and fast.
grade: devel
confinement: devmode

apps:
  app:
    command: app.out

parts:
  ai.hh:
    plugin: make
    source: https://github.com/starobinskii/AiLibrary/archive/v1.1.0.tar.gz
    build-packages:
      - g++
      - make